name: Post welcome comment
on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
  sleep:
    name: Sleep for 180 seconds
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "will sleep 180 seconds"
      - run: sleep 180s
concurrency:
  group: 'staging'
  cancel-in-progress: true
